version: "3.8"

services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:rootpassword@mysql:3306/kidohelp

  php:
    image: php:8.1-apache
    volumes:
      - ./php:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
    command: >
      sh -c "docker-php-ext-install mysqli && apache2-foreground"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kidohelp
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
